// Generated by CoffeeScript 1.8.0
(function() {
  var ActiveNav, SmoothScroll;

  ActiveNav = (function() {
    var $window, defaults, _doActive, _init, _prepareTarget;

    $window = $(window);

    _prepareTarget = function() {
      var a, i, _i, _len, _ref;
      this.targetOffset = [];
      _ref = this.$el.find('a');
      for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
        a = _ref[i];
        this.targetOffset[i] = $(a.getAttribute('href')).offset().top;
      }
    };

    _init = function() {
      return _doActive.call(this);
    };

    _doActive = function() {
      var scrollTop;
      scrollTop = $window.scrollTop();
      this.$el.find('a').removeClass(this.options.className);
      if (scrollTop < this.targetOffset[1]) {
        this.$el.find('a').eq(0).addClass(this.options.className);
      } else if ((this.targetOffset[1] <= scrollTop && scrollTop < this.targetOffset[2])) {
        this.$el.find('a').eq(1).addClass(this.options.className);
      } else if ((this.targetOffset[2] <= scrollTop && scrollTop < this.targetOffset[3])) {
        this.$el.find('a').eq(2).addClass(this.options.className);
      } else if (this.targetOffset[3] <= scrollTop) {
        this.$el.find('a').eq(3).addClass(this.options.className);
      }
    };

    defaults = {
      className: 'active'
    };

    function ActiveNav($el, options) {
      this.$el = $el;
      this.options = $.extend({}, defaults, options);
      _prepareTarget.call(this);
      _init.call(this);
      this.addEvent();
    }

    ActiveNav.prototype.addEvent = function() {
      var _this;
      _this = this;
      $window.on('scroll.activeNav', function() {
        _doActive.call(_this);
      });
      return this;
    };

    ActiveNav.prototype.removeEvent = function() {
      $window.off('scroll.activeNav');
      return this;
    };

    return ActiveNav;

  })();

  $.fn.activeNav = function(options) {
    return this.each(function(i, el) {
      var $el, activeNav;
      $el = $(el);
      if ($el.data('activeNav') == null) {
        activeNav = new ActiveNav($el, options);
        $el.data('activeNav', activeNav);
      }
    });
  };

  $('#gNav').activeNav();

  SmoothScroll = (function() {
    var defaults, _eventify, _prepareTarget;

    defaults = {
      speed: 500,
      fx: 'swing',
      onScrollBefore: null,
      onScrollAfter: null
    };

    _prepareTarget = function() {
      if (this.$el.attr('href') !== '#') {
        this.$target = $(this.$el.attr('href'));
      }
    };

    _eventify = function() {
      var _this;
      _this = this;
      this.$el.on('click.smoothScroll', function(ev) {
        ev.preventDefault();
        _this.doScroll(this);
      });
    };

    function SmoothScroll($el, options) {
      this.options = $.extend({}, defaults, options);
      this.$el = $el;
      _prepareTarget.call(this);
      _eventify.call(this);
    }

    SmoothScroll.prototype.doScroll = function(el) {
      var scrollVal, _this;
      if (!this.$target) {
        return;
      }
      _this = this;
      if (typeof _this.options.onScrollBefore === 'function') {
        _this.options.onScrollBefore(el);
      }
      scrollVal = this.$target.offset().top;
      $('html, body').stop(true, true).animate({
        scrollTop: scrollVal
      }, this.options.speed, this.options.fx).promise().done(function() {
        if (typeof _this.options.onScrollAfter === 'function') {
          _this.options.onScrollAfter(el);
        }
      });
      return this;
    };

    return SmoothScroll;

  })();

  $.fn.smoothScroll = function(options) {
    return this.each(function(i, el) {
      var $el, smoothScroll;
      $el = $(el);
      if ($el.data('smoothScroll') == null) {
        smoothScroll = new SmoothScroll($el, options);
        $el.data('smoothScroll', smoothScroll);
      }
    });
  };

  $.easing.easeOutExpo = function (x, t, b, c, d) {
  return (t==d) ? b+c : c * (-Math.pow(2, -10 * t/d) + 1) + b;
};

  $('a[href^="#"]').smoothScroll({
    speed: 1000,
    fx: 'easeOutExpo',
    onScrollBefore: function(el) {
      var activeNav;
      $('#gNav').find('a').removeClass('active');
      activeNav = $('#gNav').data('activeNav');
      activeNav.removeEvent();
      $(el).addClass('active');
    },
    onScrollAfter: function(el) {
      var activeNav;
      activeNav = $('#gNav').data('activeNav');
      activeNav.addEvent();
    }
  });

}).call(this);
