// Generated by CoffeeScript 1.8.0
(function() {
  var add, f;

  f = 1;

  add = function(x, y) {
    if (x == null) {
      x = 3;
    }
    if (y == null) {
      y = 40;
    }
    return x + y;
  };

}).call(this);
